
<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2009 Scores</b></font>
<br>
&nbsp;</p>
<div align="center">
  <table border="0" cellspacing="1" width="434" style="width: 430" bordercolor="#737373">
    <colgroup>
      <col width="178" style="width: 134pt">
      <col width="64" span="4" style="width:48pt">
    </colgroup>
    <tr height="36" style="height:27.0pt">
      <td height="36" width="178" style="height: 27.0pt; width: 134pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-style: solid; border-width: .5pt; padding: 0px; background: black">
      NET</td>
      <td width="64" style="width: 48pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;&nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      <b><font size="3">Total</font></b></td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      <b><font size="3">Day 1</font></b></td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      <b><font size="3">Day 2</font></b></td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      <b><font size="3">Day 3</font></b></td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Terry Moore</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      216</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      66</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      74</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jake Noll</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      217</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      69</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      72</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Rosas</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      223</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      85</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      64</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      74</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jim Gaines</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      226</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      72</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Ed Elliott</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      227</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      74</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      75</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Morey</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      227</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      73</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Rick McFarland</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      231</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      77</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      75</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      79</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Bob Langley</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      233</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      82</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      74</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      77</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Fenton</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      234</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      71</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      85</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Frank Carriere</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      236</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      75</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      77</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      84</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dan Needham</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      236</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      73</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      85</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jimmy McKinzie</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      237</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      80</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      81</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Al Yarbrough</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      241</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      73</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      77</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      91</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Lyn Smith</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      242</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      70</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      84</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Connie Black</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      245</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      86</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      81</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Tim Bayles</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      247</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      85</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      79</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      83</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Paul Valvo</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      248</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      73</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      87</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Scot Anderson</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      252</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      78</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      79</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      95</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      John Graves</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      264</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      81</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      95</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Randy Wheatley</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      299</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      76</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      106</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      117</td>
    </tr>
  </table>
<br><br>
  <table border="0" cellspacing="1" width="426" style="width: 430" bordercolor="#737373">
    <colgroup>
      <col width="170" style="width: 128pt">
      <col width="64" span="4" style="width:48pt">
    </colgroup>
    <tr height="36" style="height:27.0pt">
      <td height="36" width="170" style="height: 27.0pt; width: 128pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-style: solid; border-width: .5pt; padding: 0px; background: black">
      Gross</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top-style: solid; border-top-width: .5pt; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      &nbsp;</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Total</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Day 1</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Day 2</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Day 3</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Ed Elliott</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      242</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      79</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      80</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      83</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Rick McFarland</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      262</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      87</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      85</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      90</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Fenton</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      268</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      82</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      89</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      97</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Morey</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      268</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      90</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      86</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      92</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Frank Carriere</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      272</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      87</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      97</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jake Noll</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      274</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      90</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      96</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jim Gaines</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      277</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      93</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      88</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      96</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Terry Moore</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      279</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      97</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      86</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      96</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dan Needham</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      281</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      93</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      87</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      101</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Scot Anderson</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      303</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      95</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      95</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      113</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Tim Bayles</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      303</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      104</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      97</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      102</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Paul Valvo</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      308</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      108</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      92</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      108</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Connie Black</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      312</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      109</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      100</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      103</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Bob Langley</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      317</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      110</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      101</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      106</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Dave Rosas</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      319</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      117</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      96</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      106</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Jimmy McKinzie</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      326</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      109</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      110</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      107</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Al Yarbrough</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      336</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      105</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      108</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      123</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Lyn Smith</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      337</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      102</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      115</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      120</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      John Graves</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      341</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      114</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      106</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      121</td>
    </tr>
    <tr height="17" style="height:12.75pt">
      <td height="17" style="height: 12.75pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: .5pt; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      Randy Wheatley</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      369</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      100</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      129</td>
      <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none; border-right-style: solid; border-right-width: .5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: .5pt; padding: 0px; background: black">
      140</td>
    </tr>
  </table>
</div>