
<hr>
<p align="center">
<font color="#FFFFFF" size="5">2006 Scores</font></p>

<div align="center">
<table border="0" cellpadding="0" cellspacing="0" width="362" style="border-collapse:
 collapse;width:272pt">
  <colgroup>
    <col width="106" style="width: 80pt">
    <col width="64" span="4" style="width:48pt">
  </colgroup>
  <tr height="38" style="height:28.5pt">
    <td height="38" width="106" style="height: 28.5pt; width: 80pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    NET</td>
    <td width="64" style="width: 48pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;&nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Total</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 1</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 2</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 3</font></b></td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Tim Bayles</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    214</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    67</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    69</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    78</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Greg Austin</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    216</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    71</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    72</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    73</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Ed Elliott</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    223</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    72</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    75</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Bob Langley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    227</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    74</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    74</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Morey</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    227</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    71</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Rick McFarland</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    231</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    75</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Terry Moore</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    233</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    85</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    72</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Jim Gaines</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    235</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    75</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    83</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Mark Parsley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    236</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    83</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    John Graves</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    237</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    72</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    85</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Derek Underhill</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    237</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    82</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Connie Black</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    238</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Randy Wheatley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    240</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    81</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    82</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Fenton</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    243</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    73</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    89</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    81</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dan Needham</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    244</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    82</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    85</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Kirschner</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    245</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    82</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    76</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    87</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Scot Anderson</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    246</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    75</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    87</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    84</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Paul Valvo</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    247</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    88</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Lyn Smith</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    249</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    80</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    90</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Rene Almaraz</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    257</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    84</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    79</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    94</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Al Kucharski</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    262</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    87</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    92</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    83</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Average</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    237.5</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77.4</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    78.5</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    81.6</td>
  </tr>
</table>
</div>

<p align="center">&nbsp;</p>

<div align="center">
<table border="0" cellpadding="0" cellspacing="0" width="362" style="border-collapse:
 collapse;width:272pt">
  <colgroup>
    <col width="106" style="width: 80pt">
    <col width="64" span="4" style="width:48pt">
  </colgroup>
  <tr height="38" style="height:28.5pt">
    <td height="38" width="106" style="height: 28.5pt; width: 80pt; color: white; font-size: 22.0pt; font-family: Arial, sans-serif; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Gross</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Palmer</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Ledges</td>
    <td width="64" style="width: 48pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top-style: solid; border-top-width: 1.5pt; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Wolf Creek</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Total</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 1</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 2</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <b><font size="3">Day 3</font></b></td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Ed Elliott</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    240</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    77</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    82</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    81</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Rick McFarland</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    259</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    85</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    84</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    90</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Mark Parsley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    268</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    87</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    87</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    94</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Morey</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    277</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    92</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    88</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    97</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Greg Austin</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    282</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    92</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    94</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    96</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Tim Bayles</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    283</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    89</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    92</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    102</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dan Needham</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    287</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    91</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    96</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    100</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Fenton</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    289</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    88</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    97</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    John Graves</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    292</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    90</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    98</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Connie Black</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    294</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    97</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    99</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    98</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Jim Gaines</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    297</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    97</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    96</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Derek Underhill</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    297</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    101</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    99</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    97</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Scot Anderson</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    303</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    93</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    106</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Terry Moore</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    305</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    108</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    96</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    101</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Paul Valvo</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    307</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    98</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    108</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    101</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Bob Langley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    308</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    100</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    101</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    107</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Randy Wheatley</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    312</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    101</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    107</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Al Kucharski</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    322</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    106</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    112</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    104</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Rene Almaraz</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    327</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    106</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    103</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    118</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Dave Kirschner</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    333</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    110</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    105</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    118</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    Lyn Smith</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    347</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    111</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    112</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    124</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    &nbsp;</td>
  </tr>
  <tr height="19" style="height:14.25pt">
    <td height="19" style="height: 14.25pt; color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-width: 1.5pt; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    <p style="text-align: left">
    <b><font size="3">Average</font></b></td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    296.6</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    96.3</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    98.2</td>
    <td style="color: white; font-family: Arial, sans-serif; text-align: center; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left: medium none #808080; border-right: 1.5pt solid #808080; border-top: medium none #808080; border-bottom: 1.5pt solid #808080; padding-left: 1px; padding-right: 1px; padding-top: 1px; background: black">
    102.1</td>
  </tr>
</table>
</div>