<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2014 Scores</b></font>
<br></p>
      
<div align="center">
<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  NET</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr> 

<tr><td>Grant Larson G</td><td>221</td><td>75</td><td>71</td><td>75</td><td></td></tr>
<tr><td>Dan  Needham</td><td>229</td><td>70</td><td>78</td><td>81</td><td></td></tr>
<tr><td>David  Bunker D</td><td>230</td><td>75</td><td>73</td><td>82</td><td></td></tr>
<tr><td>Matt Whitney</td><td>240</td><td>74</td><td>80</td><td>86</td><td></td></tr>
<tr><td>Shannon Hill</td><td>242</td><td>78</td><td>82</td><td>82</td><td>Tie</td></tr>
<tr><td>Bob Langley</td><td>242</td><td>74</td><td>81</td><td>87</td><td></td></tr>
<tr><td>Howard Stoddard</td><td>244</td><td>81</td><td>87</td><td>76</td><td></td></tr>
<tr><td>Frank Carriere</td><td>246</td><td>76</td><td>81</td><td>89</td><td></td></tr>
<tr><td>Jim  Coffee</td><td>246</td><td>77</td><td>77</td><td>92</td><td></td></tr>
<tr><td>Scot Anderson</td><td>247</td><td>84</td><td>83</td><td>80</td><td>Tie</td></tr>
<tr><td>Omel Cardenas</td><td>247</td><td>88</td><td>77</td><td>82</td><td></td></tr>
<tr><td>Stewart Sampson</td><td>249</td><td>79</td><td>84</td><td>86</td><td></td></tr>
<tr><td>Eric Larson E</td><td>250</td><td>82</td><td>80</td><td>88</td><td></td></tr>
<tr><td>Patrick Buckley</td><td>251</td><td>90</td><td>84</td><td>77</td><td></td></tr>
<tr><td>Tim Bayles</td><td>255</td><td>78</td><td>89</td><td>88</td><td>Tie</td></tr>
<tr><td>Connie Black</td><td>255</td><td>90</td><td>89</td><td>76</td><td></td></tr>
<tr><td>Jimmy McKinzie</td><td>258</td><td>89</td><td>90</td><td>79</td><td>Tie</td></tr>
<tr><td>Paul  Valvo</td><td>258</td><td>89</td><td>84</td><td>85</td><td></td></tr>
<tr><td>Dave Rosas</td><td>262</td><td>89</td><td>87</td><td>86</td><td></td></tr>
<tr><td>Ron Watson</td><td>264</td><td>89</td><td>88</td><td>87</td><td></td></tr>
<tr><td>Danny  Baird</td><td>266</td><td>88</td><td>81</td><td>97</td><td></td></tr>
<tr><td>Bo  Bunker B</td><td>305</td><td>83</td><td>102</td><td>120</td><td></td></tr>
<tr><td>Randy Wheatley</td><td>345</td><td>97</td><td>124</td><td>124</td><td></td></tr>

</table>


















<br/><br/>






<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  Gross</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr>

<tr><td>Grant Larson G</td><td>258</td><td>88</td><td>83</td><td>87</td><td></td></tr>
<tr><td>Dan  Needham</td><td>277</td><td>86</td><td>94</td><td>97</td><td></td></tr>
<tr><td>David  Bunker D</td><td>283</td><td>93</td><td>91</td><td>99</td><td></td></tr>
<tr><td>Frank Carriere</td><td>295</td><td>93</td><td>97</td><td>105</td><td></td></tr>
<tr><td>Shannon Hill</td><td>297</td><td>97</td><td>100</td><td>100</td><td></td></tr>
<tr><td>Scot Anderson</td><td>302</td><td>103</td><td>101</td><td>98</td><td></td></tr>
<tr><td>Connie Black</td><td>307</td><td>108</td><td>106</td><td>93</td><td></td></tr>
<tr><td>Stewart Sampson</td><td>319</td><td>103</td><td>107</td><td>109</td><td></td></tr>
<tr><td>Ron Watson</td><td>319</td><td>108</td><td>106</td><td>105</td><td></td></tr>
<tr><td>Danny  Baird</td><td>321</td><td>107</td><td>99</td><td>115</td><td></td></tr>
<tr><td>Howard Stoddard</td><td>323</td><td>108</td><td>113</td><td>102</td><td>Tie</td></tr>
<tr><td>Matt Whitney</td><td>323</td><td>103</td><td>107</td><td>113</td><td></td></tr>
<tr><td>Jim  Coffee</td><td>328</td><td>105</td><td>104</td><td>119</td><td></td></tr>
<tr><td>Omel Cardenas</td><td>329</td><td>116</td><td>104</td><td>109</td><td></td></tr>
<tr><td>Tim Bayles</td><td>331</td><td>104</td><td>114</td><td>113</td><td>Tie</td></tr>
<tr><td>Eric Larson E</td><td>331</td><td>111</td><td>106</td><td>114</td><td></td></tr>
<tr><td>Bob Langley</td><td>332</td><td>105</td><td>110</td><td>117</td><td></td></tr>
<tr><td>Paul  Valvo</td><td>334</td><td>115</td><td>109</td><td>110</td><td></td></tr>
<tr><td>Patrick Buckley</td><td>335</td><td>119</td><td>111</td><td>105</td><td></td></tr>
<tr><td>Jimmy McKinzie</td><td>339</td><td>117</td><td>116</td><td>106</td><td></td></tr>
<tr><td>Dave Rosas</td><td>343</td><td>117</td><td>113</td><td>113</td><td></td></tr>
<tr><td>Bo  Bunker B</td><td>377</td><td>108</td><td>125</td><td>144</td><td></td></tr>
<tr><td>Randy Wheatley</td><td>406</td><td>118</td><td>144</td><td>144</td><td></td></tr>
</table>


</div>