<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2011 Scores</b></font>
<br></p>
      
<div align="center">
 <table width="430" class="score">
    <tr>
      <td colwidth="5" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
      NET</td>
    </tr>
    <tr>
      <td colwidth="5"></td>
    </tr>
    <tr>
      <th>Player</th>
      <th>Total</th>
      <th>Day 1</th>
      <th>Day 2</th>
      <th>Day 3</th>
    </tr>
<tr><td>Lyn Smith</td><td>220</td><td>71</td><td>62</td><td>87</td></tr>
<tr><td>Ken Silver</td><td>223</td><td>75</td><td>71</td><td>77</td></tr>
<tr><td>Kevin Kleifges</td><td>227</td><td>70</td><td>71</td><td>86</td></tr>
<tr><td>Frank Carriere</td><td>229</td><td>71</td><td>77</td><td>81</td></tr>
<tr><td>Rick  McFarland</td><td>232</td><td>78</td><td>81</td><td>73</td></tr>
<tr><td>Eric Hilberath</td><td>237</td><td>85</td><td>69</td><td>83</td></tr>
<tr><td>Connie Black</td><td>241</td><td>74</td><td>84</td><td>83</td></tr>
<tr><td>Jason Myers</td><td>244</td><td>74</td><td>80</td><td>90</td></tr>
<tr><td>Al  Yarbrough</td><td>244</td><td>71</td><td>84</td><td>89</td></tr>
<tr><td>Pat Buckley</td><td>246</td><td>84</td><td>72</td><td>90</td></tr>
<tr><td>Bob Langley</td><td>246</td><td>77</td><td>84</td><td>85</td></tr>
<tr><td>Dan Needham</td><td>246</td><td>74</td><td>84</td><td>88</td></tr>
<tr><td>Randy Wheatley</td><td>248</td><td>84</td><td>83</td><td>81</td></tr>
<tr><td>Dave Rosas</td><td>249</td><td>89</td><td>77</td><td>83</td></tr>
<tr><td>Gavin Russo</td><td>250</td><td>76</td><td>85</td><td>89</td></tr>
<tr><td>Eric Larson</td><td>252</td><td>84</td><td>85</td><td>83</td></tr>
<tr><td>Scot Anderson</td><td>253</td><td>81</td><td>82</td><td>90</td></tr>
<tr><td>Jimmy McKinzie</td><td>258</td><td>82</td><td>89</td><td>87</td></tr>
<tr><td>Stewart  Sampson</td><td>259</td><td>83</td><td>84</td><td>92</td></tr>
<tr><td>Tim Bayles</td><td>262</td><td>89</td><td>79</td><td>94</td></tr>
<tr><td>Rene Almaraz</td><td>263</td><td>83</td><td>83</td><td>97</td></tr>
<tr><td>Paul  Valvo</td><td>263</td><td>81</td><td>86</td><td>96</td></tr>
<tr><td>Robert Guthrie</td><td>264</td><td>83</td><td>95</td><td>86</td></tr>
<tr><td>Roland Gonzales</td><td>279</td><td>85</td><td>93</td><td>101</td></tr>
</table>
















<br><br>






 <table width="430" class="score">
    <tr>
      <td colwidth="5" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
      Gross</td>
    </tr>
    <tr>
      <td colwidth="5"></td>
    </tr>
    <tr>
      <th>Player</th>
      <th>Total</th>
      <th>Day 1</th>
      <th>Day 2</th>
      <th>Day 3</th>
    </tr>
<tr><td>Kevin Kleifges</td><td>259</td><td>80</td><td>82</td><td>97</td></tr>
<tr><td>Frank Carriere</td><td>263</td><td>82</td><td>89</td><td>92</td></tr>
<tr><td>Rick  McFarland</td><td>269</td><td>90</td><td>94</td><td>85</td></tr>
<tr><td>Ken Silver</td><td>274</td><td>91</td><td>89</td><td>94</td></tr>
<tr><td>Eric Hilberath</td><td>277</td><td>98</td><td>83</td><td>96</td></tr>
<tr><td>Connie Black</td><td>284</td><td>88</td><td>99</td><td>97</td></tr>
<tr><td>Jason Myers</td><td>284</td><td>87</td><td>94</td><td>103</td></tr>
<tr><td>Gavin Russo</td><td>284</td><td>87</td><td>97</td><td>100</td></tr>
<tr><td>Dan Needham</td><td>287</td><td>87</td><td>98</td><td>102</td></tr>
<tr><td>Scot Anderson</td><td>288</td><td>92</td><td>94</td><td>102</td></tr>
<tr><td>Randy Wheatley</td><td>304</td><td>102</td><td>102</td><td>100</td></tr>
<tr><td>Stewart  Sampson</td><td>310</td><td>99</td><td>102</td><td>109</td></tr>
<tr><td>Eric Larson</td><td>311</td><td>103</td><td>105</td><td>103</td></tr>
<tr><td>Paul  Valvo</td><td>311</td><td>96</td><td>103</td><td>112</td></tr>
<tr><td>Robert Guthrie</td><td>313</td><td>99</td><td>112</td><td>102</td></tr>
<tr><td>Tim Bayles</td><td>314</td><td>106</td><td>97</td><td>111</td></tr>
<tr><td>Pat Buckley</td><td>318</td><td>107</td><td>97</td><td>114</td></tr>
<tr><td>Bob Langley</td><td>318</td><td>100</td><td>109</td><td>109</td></tr>
<tr><td>Dave Rosas</td><td>318</td><td>111</td><td>101</td><td>106</td></tr>
<tr><td>Rene Almaraz</td><td>320</td><td>101</td><td>103</td><td>116</td></tr>
<tr><td>Lyn Smith</td><td>321</td><td>103</td><td>97</td><td>121</td></tr>
<tr><td>Al  Yarbrough</td><td>328</td><td>98</td><td>113</td><td>117</td></tr>
<tr><td>Jimmy McKinzie</td><td>336</td><td>107</td><td>116</td><td>113</td></tr>
<tr><td>Roland Gonzales</td><td>348</td><td>107</td><td>117</td><td>124</td></tr>
</table>

</div>