<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2002 Scores</b></font>
<br>
&nbsp;</p>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 644" height="41" bordercolor="#737373">
    <colgroup>
      <col width="121" style="width: 91pt"><col width="78" style="width: 59pt">
      <col width="90" style="width: 68pt"><col width="63" style="width: 47pt">
      <col width="65" style="width: 49pt"><col width="73" style="width: 55pt">
      <col width="51" style="width: 38pt">
      <col width="51" style="width: 38pt">
    </colgroup>
    <tr>
      <td width="118" style="border-color:inherit; height: 32; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px">
      <font color="#FFFFFF">Name</font></td>
      <td style="border-color:inherit; width: 103; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Gross</font></td>
      <td style="border-color:inherit; width: 83; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Handicap</font></td>
      <td width="63" style="border-color:inherit; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Net</font></td>
      <td style="border-color:inherit; width: 64; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Skins</font></td>
      <td style="border-color:inherit; width: 69; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Cum Gross</font></td>
      <td style="border-color:inherit; width: 53; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Cum Net</font></td>
      <td style="border-color:inherit; width: 91; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="32">
      <font color="#FFFFFF">Award</font></td>
    </tr>
    <tr height="42" style="height:31.5pt">
      <td width="118" style="border-color:inherit; height: 9; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px">&nbsp;</td>
      <td style="border-color:inherit; width: 103; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td style="border-color:inherit; width: 82; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td width="61" style="border-color:inherit; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td style="border-color:inherit; width: 60; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td style="border-color:inherit; width: 72; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td style="border-color:inherit; width: 55; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
      <td style="border-color:inherit; width: 96; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; padding-left: 0px; padding-right: 0px; padding-top: 0px" height="9">
      </td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 644" bordercolor="#737373">
    <colgroup>
      <col width="121" style="width: 91pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; width: 587; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: medium none; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/12/2002&nbsp;&nbsp;&nbsp;&nbsp; Course: Casa Blanca&nbsp;&nbsp;&nbsp;&nbsp; Slope: 
      126&nbsp;&nbsp;&nbsp;&nbsp; Par: 72</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse; " bordercolor="#737373" width="644">
    <colgroup>
      <col width="121" style="width: 91pt"><col width="78" style="width: 59pt">
      <col width="90" style="width: 68pt"><col width="63" style="width: 47pt">
      <col width="65" style="width: 49pt"><col width="73" style="width: 55pt">
      <col width="51" style="width: 38pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td height="19" width="118" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Anderson, Bob</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">112</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" x:num x:fmla="=B1-D1" width="83">
      <font color="#FFFFFF">24</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">88</font></td>
      <td width="64" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td width="69" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" x:num>
      <font color="#FFFFFF">333</font></td>
      <td width="53" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" x:num>
      <font color="#FFFFFF">261</font></td>
      <td width="91" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">98</font></td>
      <td x:num x:fmla="=B2-D2" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">16</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">82</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">281</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">230</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Carriere, Frank</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">81</font></td>
      <td x:num x:fmla="=B3-D3" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">11</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">70</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">2</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">261</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">229</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Elliott, Ed</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">86</font></td>
      <td x:fmla="=B4-D4" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">5</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">81</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">237</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: top; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">219</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      <font color="#FFFFFF" style="font-size: 8pt"><b>Champion - Gross</b></font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Fenton, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">89</font></td>
      <td x:num x:fmla="=B5-D5" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">16</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">73</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">262</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">214</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      <font color="#FFFFFF">2nd</font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Graves, John</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">95</font></td>
      <td x:num x:fmla="=B6-D6" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">12</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">83</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">283</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">250</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Hannigriff, Rich</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">77</font></td>
      <td x:num x:fmla="=B7-D7" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">8</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">69</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">241</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">214</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      <font color="#FFFFFF" style="font-size: 8pt; font-weight:700">Champion - Net</font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">101</font></td>
      <td x:num x:fmla="=B8-D8" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">23</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">78</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">300</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">230</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">95</font></td>
      <td x:num x:fmla="=B9-D9" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">19</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">285</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">223</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Morey, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">90</font></td>
      <td x:num x:fmla="=B10-D10" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">22</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">68</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">286</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">219</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      <font color="#FFFFFF">3rd</font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">105</font></td>
      <td x:num x:fmla="=B11-D11" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">35</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">70</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">2</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">340</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">235</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Swauger, David</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">108</font></td>
      <td x:num x:fmla="=B12-D12" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">30</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">
      <font color="#FFFFFF">78</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">3</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">338</font></td>
      <td x:num style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">247</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">&nbsp;</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">&nbsp;</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td colspan="2" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:num="94.75" x:fmla="=AVERAGE(B1:B12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bgcolor="#737373">
      <font color="#FFFFFF">94.8</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="18.416666666666668" x:fmla="=AVERAGE(C1:C12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bgcolor="#737373">
      <font color="#FFFFFF">18.4</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="76.333333333333329" x:fmla="=AVERAGE(D1:D12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bgcolor="#737373">
      <font color="#FFFFFF">76.3</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 644">
    <colgroup>
      <col width="121" style="width: 91pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; width: 566; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/11/2002&nbsp;&nbsp;&nbsp;&nbsp; Course: Coral Canyon&nbsp;&nbsp;&nbsp;&nbsp; 
      Slope: 135&nbsp;&nbsp;&nbsp;&nbsp; Par: 72</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-style:solid; border-collapse: collapse; width: 644" bordercolor="#737373">
    <colgroup>
      <col width="121" style="width: 91pt"><col width="78" style="width: 59pt">
      <col width="90" style="width: 68pt"><col width="63" style="width: 47pt">
      <col width="65" style="width: 49pt"><col width="73" style="width: 55pt">
      <col width="51" style="width: 38pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; width: 118; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Anderson, Bob</font></td>
      <td style="border-color:inherit; width: 103; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">109</font></td>
      <td style="border-color:inherit; width: 83; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">24</font></td>
      <td style="border-color:inherit; width: 63; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">85</font></td>
      <td style="border-color:inherit; width: 64; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="border-color:inherit; width: 69; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">221</font></td>
      <td style="border-color:inherit; width: 53; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">173</font></td>
      <td style="border-color:inherit; width: 91; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">86</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">17</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">69</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">183</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">148</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Carriere, Frank</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">86</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">11</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">75</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">180</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">159</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Elliott, Ed</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">75</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">6</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">69</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">151</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">138</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Fenton, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">90</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">14</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">173</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">141</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Graves, John</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">93</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">11</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">82</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">188</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">167</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Hannigriff, Rich</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">77</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">9</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">68</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">164</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">145</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">98</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">22</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">199</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">152</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">88</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">20</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">68</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">190</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">147</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Morey, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">97</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">21</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">2</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">196</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">151</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">113</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">34</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">79</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">235</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">165</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">
      <font color="#FFFFFF">Swauger, David</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">
      <font color="#FFFFFF">110</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">
      <font color="#FFFFFF">30</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">
      <font color="#FFFFFF">80</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">
      <font color="#FFFFFF">230</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">
      <font color="#FFFFFF">169</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">
      &nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td colspan="2" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:fmla="=AVERAGE(B1:B12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63" bgcolor="#737373">
      <font color="#FFFFFF">93.5</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="18.25" x:fmla="=AVERAGE(C1:C12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63" bgcolor="#737373">
      <font color="#FFFFFF">18.3</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="75.25" x:fmla="=AVERAGE(D1:D12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63" bgcolor="#737373">
      <font color="#FFFFFF">75.3</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="118">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="63">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="64">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="69">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="53">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="91">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 644">
    <colgroup>
      <col width="121" style="width: 91pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; width: 568; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/10/2002&nbsp;&nbsp;&nbsp;&nbsp; Course: Wolf Creek&nbsp;&nbsp;&nbsp;&nbsp; Slope: 
      138&nbsp;&nbsp;&nbsp;&nbsp; Par: 72</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 644" bordercolor="#CACACA">
    <colgroup>
      <col width="121" style="width: 91pt"><col width="78" style="width: 59pt">
      <col width="90" style="width: 68pt"><col width="63" style="width: 47pt">
      <col width="65" style="width: 49pt"><col width="73" style="width: 55pt">
      <col width="51" style="width: 38pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td height="19" width="121" style="border-color:inherit; height: 14.25pt; width: 118; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Anderson, Bob</font></td>
      <td style="border-color:inherit; width: 103; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">112</font></td>
      <td style="border-color:inherit; width: 83; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">24</font></td>
      <td width="63" style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">88</font></td>
      <td width="65" style="border-color:inherit; width: 64; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td width="73" style="border-color:inherit; width: 69; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td width="51" style="border-color:inherit; width: 53; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td width="51" style="border-color:inherit; width: 91; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">97</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">18</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">79</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Carriere, Frank</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">94</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">10</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">84</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Elliott, Ed</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">7</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">69</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Fenton, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">83</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">18</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">65</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Graves, John</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">95</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">10</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">85</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Hannigriff, Rich</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">87</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">10</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">77</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">101</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">25</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">76</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">102</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">23</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">79</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Morey, Dave</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">99</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">24</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">75</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">
      <font color="#FFFFFF">1</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">122</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">36</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">86</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">
      <font color="#FFFFFF">Swauger, David</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">120</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">
      <font color="#FFFFFF">31</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">89</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">&nbsp;</td>
      <td colspan="2" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:fmla="=AVERAGE(B1:B12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">99.0</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="19.666666666666668" x:fmla="=AVERAGE(C1:C12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">19.7</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="border-color:inherit; height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:118" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="83" bgcolor="#737373">&nbsp;</td>
      <td x:num="79.333333333333329" x:fmla="=AVERAGE(D1:D12)" style="border-color:inherit; font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bgcolor="#737373">
      <font color="#FFFFFF">79.3</font></td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:64" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:69" bordercolor="#737373">&nbsp;</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px; width:53" bordercolor="#737373">
      \</td>
      <td style="border-color:inherit; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" width="91">
      &nbsp;</td>
    </tr>
  </table>
  </center>
</div>