<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2013 Scores</b></font>
<br></p>
      
<div align="center">
<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  NET</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr> 
<tr><td>Frank Carriere</td><td>211</td><td>73</td><td>73</td><td>65</td><td></td></tr>
<tr><td>Randy Wheatley</td><td>212</td><td>66</td><td>71</td><td>75</td><td></td></tr>
<tr><td>Eric Larson</td><td>213</td><td>74</td><td>71</td><td>68</td><td></td></tr>
<tr><td>Bob Langley</td><td>215</td><td>71</td><td>74</td><td>70</td><td>Tie</td></tr>
<tr><td>Mark Parsley</td><td>215</td><td>77</td><td>71</td><td>67</td><td></td></tr>
<tr><td>Danny Baird</td><td>216</td><td>74</td><td>80</td><td>62</td><td>Tie</td></tr>
<tr><td>Tim Bayles</td><td>216</td><td>76</td><td>68</td><td>72</td><td></td></tr>
<tr><td>Jason Carmack</td><td>217</td><td>72</td><td>76</td><td>69</td><td></td></tr>
<tr><td>Rick McFarland</td><td>219</td><td>71</td><td>84</td><td>64</td><td></td></tr>
<tr><td>Omel Cardenas</td><td>221</td><td>76</td><td>73</td><td>72</td><td>Tie</td></tr>
<tr><td>Jim Coffey</td><td>221</td><td>79</td><td>66</td><td>76</td><td></td></tr>
<tr><td>Lny Smith</td><td>222</td><td>78</td><td>75</td><td>69</td><td></td></tr>
<tr><td>David Bunker</td><td>223</td><td>69</td><td>84</td><td>70</td><td></td></tr>
<tr><td>Kirk Smart</td><td>226</td><td>78</td><td>78</td><td>70</td><td></td></tr>
<tr><td>Tom Dransfield</td><td>227</td><td>74</td><td>77</td><td>76</td><td></td></tr>
<tr><td>Dan Needham</td><td>231</td><td>77</td><td>83</td><td>71</td><td>Tie</td></tr>
<tr><td>Stewart Sampson</td><td>231</td><td>70</td><td>89</td><td>72</td><td></td></tr>
<tr><td>Dave Rosas</td><td>232</td><td>71</td><td>87</td><td>74</td><td></td></tr>
<tr><td>Jimmy McKinzie</td><td>234</td><td>81</td><td>72</td><td>81</td><td></td></tr>
<tr><td>Gary Frick</td><td>238</td><td>74</td><td>81</td><td>83</td><td></td></tr>
<tr><td>Pat Buckley</td><td>239</td><td>80</td><td>79</td><td>80</td><td></td></tr>
<tr><td>Robert Guthrie</td><td>243</td><td>82</td><td>76</td><td>85</td><td></td></tr>
<tr><td>Paul Valvo</td><td>248</td><td>81</td><td>87</td><td>80</td><td></td></tr>
<tr><td>Shannon Hill</td><td>249</td><td>82</td><td>85</td><td>82</td><td></td></tr>
<tr><td>Connie Black</td><td>251</td><td>85</td><td>88</td><td>78</td><td></td></tr>
<tr><td>Bob Rhinehart</td><td>266</td><td>92</td><td>95</td><td>79</td><td></td></tr>
</table>


















<br/><br/>






<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  Gross</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr> 
<tr><td>Mark Parsley</td><td>249</td><td>88</td><td>83</td><td>78</td><td></td></tr>
<tr><td>Tom Dransfield</td><td>251</td><td>82</td><td>85</td><td>84</td><td></td></tr>
<tr><td>Jason Carmack</td><td>254</td><td>84</td><td>89</td><td>81</td><td></td></tr>
<tr><td>Rick  McFarland</td><td>258</td><td>84</td><td>97</td><td>77</td><td></td></tr>
<tr><td>Randy Wheatley</td><td>273</td><td>86</td><td>92</td><td>95</td><td></td></tr>
<tr><td>David Bunker</td><td>278</td><td>87</td><td>103</td><td>88</td><td>Tie</td></tr>
<tr><td>Frank Carriere</td><td>278</td><td>95</td><td>96</td><td>87</td><td></td></tr>
<tr><td>Dan Needham</td><td>280</td><td>93</td><td>100</td><td>87</td><td></td></tr>
<tr><td>Tim Bayles</td><td>282</td><td>98</td><td>90</td><td>94</td><td></td></tr>
<tr><td>Gary Frick</td><td>287</td><td>90</td><td>98</td><td>99</td><td></td></tr>
<tr><td>Shannon Hill</td><td>294</td><td>97</td><td>100</td><td>97</td><td></td></tr>
<tr><td>Connie Black</td><td>300</td><td>101</td><td>105</td><td>94</td><td></td></tr>
<tr><td>Danny Baird</td><td>302</td><td>102</td><td>109</td><td>91</td><td></td></tr>
<tr><td>Jim  Coffey</td><td>307</td><td>107</td><td>95</td><td>105</td><td></td></tr>
<tr><td>Omel Cardenas</td><td>310</td><td>105</td><td>103</td><td>102</td><td>Tie</td></tr>
<tr><td>Stewart Sampson</td><td>310</td><td>96</td><td>116</td><td>98</td><td>Tie</td></tr>
<tr><td>Paul  Valvo</td><td>310</td><td>101</td><td>108</td><td>101</td><td></td></tr>
<tr><td>Robert Guthrie</td><td>314</td><td>105</td><td>100</td><td>109</td><td></td></tr>
<tr><td>Bob Langley</td><td>318</td><td>105</td><td>109</td><td>104</td><td></td></tr>
<tr><td>Eric Larson</td><td>319</td><td>109</td><td>107</td><td>103</td><td></td></tr>
<tr><td>Jimmy McKinzie</td><td>322</td><td>110</td><td>102</td><td>110</td><td></td></tr>
<tr><td>Kirk Smart</td><td>323</td><td>110</td><td>111</td><td>102</td><td></td></tr>
<tr><td>Dave Rosas</td><td>325</td><td>101</td><td>119</td><td>105</td><td>Tie</td></tr>
<tr><td>Lny Smith</td><td>325</td><td>112</td><td>110</td><td>103</td><td></td></tr>
<tr><td>Pat  Buckley</td><td>336</td><td>112</td><td>112</td><td>112</td><td></td></tr>
<tr><td>Bob Rhinehart</td><td>357</td><td>122</td><td>126</td><td>109</td><td></td></tr>
</table>

</div>