<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2010 Scores</b></font>
<br></p>
      
<div align="center">
 <table width="430" class="score">
    <tr>
      <td colwidth="5" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
      NET</td>
    </tr>
    <tr>
      <td colwidth="5"></td>
    </tr>
    <tr>
      <th>Player</th>
      <th>Total</th>
      <th>Day 1</th>
      <th>Day 2</th>
      <th>Day 3</th>
    </tr>
    <tr><td>Rick  McFarland</td><td>211</td><td>65</td><td>78</td><td>68</td></tr>
<tr><td>Jim  Gaines</td><td>223</td><td>74</td><td>75</td><td>74</td></tr>
<tr><td>Frank Carriere</td><td>227</td><td>75</td><td>75</td><td>77</td></tr>
<tr><td>Al  Yarbrough</td><td>227</td><td>74</td><td>75</td><td>78</td></tr>
<tr><td>Ed  Elliott</td><td>228</td><td>75</td><td>77</td><td>76</td></tr>
<tr><td>Connie Black</td><td>230</td><td>77</td><td>82</td><td>71</td></tr>
<tr><td>Terry Moore</td><td>231</td><td>75</td><td>81</td><td>75</td></tr>
<tr><td>Lyn Smith</td><td>232</td><td>74</td><td>77</td><td>81</td></tr>
<tr><td>Stewart  Sampson</td><td>235</td><td>81</td><td>71</td><td>83</td></tr>
<tr><td>Robert Guthrie</td><td>236</td><td>79</td><td>71</td><td>86</td></tr>
<tr><td>Tim Bayles</td><td>237</td><td>68</td><td>82</td><td>87</td></tr>
<tr><td>Mark  Parsley-Bl</td><td>240</td><td>79</td><td>79</td><td>82</td></tr>
<tr><td>Rene Almaraz</td><td>244</td><td>78</td><td>84</td><td>82</td></tr>
<tr><td>Al  Kucharski</td><td>247</td><td>77</td><td>83</td><td>87</td></tr>
<tr><td>Jimmy McKinzie</td><td>249</td><td>79</td><td>80</td><td>90</td></tr>
<tr><td>Dave  Fenton</td><td>250</td><td>81</td><td>85</td><td>84</td></tr>
<tr><td>Eric Larson</td><td>250</td><td>80</td><td>85</td><td>85</td></tr>
<tr><td>Ken Silver</td><td>250</td><td>87</td><td>79</td><td>84</td></tr>
<tr><td>Bob Langley</td><td>254</td><td>84</td><td>81</td><td>89</td></tr>
<tr><td>Dan Needham</td><td>254</td><td>82</td><td>90</td><td>82</td></tr>
<tr><td>Dave  Rosas</td><td>256</td><td>88</td><td>80</td><td>88</td></tr>
<tr><td>Scot Anderson</td><td>261</td><td>88</td><td>84</td><td>89</td></tr>
<tr><td>Pat Buckley</td><td>263</td><td>81</td><td>85</td><td>97</td></tr>
<tr><td>Roland Gonzales</td><td>269</td><td>94</td><td>85</td><td>90</td></tr>
<tr><td>Jim Coffey</td><td>275</td><td>91</td><td>87</td><td>97</td></tr>
<tr><td>Paul  Valvo</td><td>278</td><td>86</td><td>92</td><td>100</td></tr>
<tr><td>John Graves</td><td>284</td><td>96</td><td>93</td><td>95</td></tr>
<tr><td>Randy Wheatley</td><td>293</td><td>94</td><td>123</td><td>76</td></tr>
  </table>
















<br><br>






 <table width="430" class="score">
    <tr>
      <td colwidth="5" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
      Gross</td>
    </tr>
    <tr>
      <td colwidth="5"></td>
    </tr>
    <tr>
      <th>Player</th>
      <th>Total</th>
      <th>Day 1</th>
      <th>Day 2</th>
      <th>Day 3</th>
    </tr>
<tr><td>Ed Elliott</td><td>237</td><td>78</td><td>80</td><td>79</td></tr>
<tr><td>Rick McFarland</td><td>247</td><td>77</td><td>90</td><td>80</td></tr>
<tr><td>Jim Gaines</td><td>262</td><td>87</td><td>88</td><td>87</td></tr>
<tr><td>Frank Carriere</td><td>266</td><td>88</td><td>88</td><td>90</td></tr>
<tr><td>Mark Parsley-Bl</td><td>267</td><td>88</td><td>88</td><td>91</td></tr>
<tr><td>Dave Fenton</td><td>277</td><td>90</td><td>94</td><td>93</td></tr>
<tr><td>Connie Black</td><td>281</td><td>94</td><td>99</td><td>88</td></tr>
<tr><td>Dan Needham</td><td>284</td><td>92</td><td>100</td><td>92</td></tr>
<tr><td>Tim Bayles</td><td>285</td><td>84</td><td>98</td><td>103</td></tr>
<tr><td>Stewart Sampson</td><td>286</td><td>98</td><td>88</td><td>100</td></tr>
<tr><td>Terry Moore</td><td>288</td><td>94</td><td>100</td><td>94</td></tr>
<tr><td>Ken Silver</td><td>292</td><td>101</td><td>93</td><td>98</td></tr>
<tr><td>Rene Almaraz</td><td>295</td><td>95</td><td>101</td><td>99</td></tr>
<tr><td>Robert Guthrie</td><td>296</td><td>99</td><td>91</td><td>106</td></tr>
<tr><td>Scot Anderson</td><td>303</td><td>102</td><td>98</td><td>103</td></tr>
<tr><td>Al Kucharski</td><td>307</td><td>97</td><td>103</td><td>107</td></tr>
<tr><td>Eric Larson</td><td>313</td><td>101</td><td>106</td><td>106</td></tr>
<tr><td>Bob Langley</td><td>323</td><td>107</td><td>104</td><td>112</td></tr>
<tr><td>Paul Valvo</td><td>323</td><td>101</td><td>107</td><td>115</td></tr>
<tr><td>Al Yarbrough</td><td>323</td><td>106</td><td>107</td><td>110</td></tr>
<tr><td>Jimmy McKinzie</td><td>324</td><td>104</td><td>105</td><td>115</td></tr>
<tr><td>Pat Buckley</td><td>326</td><td>102</td><td>106</td><td>118</td></tr>
<tr><td>Dave  Rosas</td><td>328</td><td>112</td><td>104</td><td>112</td></tr>
<tr><td>Lyn Smith</td><td>331</td><td>107</td><td>110</td><td>114</td></tr>
<tr><td>Jim Coffey</td><td>341</td><td>113</td><td>109</td><td>119</td></tr>
<tr><td>John Graves</td><td>344</td><td>116</td><td>113</td><td>115</td></tr>
<tr><td>Randy Wheatley</td><td>353</td><td>114</td><td>143</td><td>96</td></tr>
<tr><td>Roland Gonzales</td><td>368</td><td>127</td><td>118</td><td>123</td></tr>

  </table>
</div>