
<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2008 Scores</b></font>
<br>
&nbsp;</p>
<div align="center">
  <table class="MsoNormalTable" border="1" cellspacing="0" cellpadding="0" style="width: 430; border-collapse: collapse; border: medium none; margin-left: 4.65pt" bordercolor="#737373">
 <col width=104 style='mso-width-source:userset;mso-width-alt:3803;width:78pt'>
 <col width=64 span=4 style='width:48pt'>
 <tr height=36 style='height:27.0pt'>
      <td nowrap style="width: 132; height: 27.75pt; border-style: solid; border-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 22.0pt; font-family: Arial,sans-serif; color: white">NET</span></td>
  <td class=xl66 width=64 style='border-left:medium none;height:27.75pt; border-right-style:solid; border-right-width:1.5pt; border-top-style:solid; border-top-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; color: white"> </span></td>
  <td class=xl67 width=64 style='border-left:medium none;height:27.75pt; border-right-style:solid; border-right-width:1.5pt; border-top-style:solid; border-top-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl67 width=64 style='border-left:medium none;height:27.75pt; border-right-style:solid; border-right-width:1.5pt; border-top-style:solid; border-top-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl67 width=64 style='border-left:medium none;height:27.75pt; border-right-style:solid; border-right-width:1.5pt; border-top-style:solid; border-top-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">&nbsp;</span></td>
  <td class=xl67 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <font color="#FFFFFF">  </font></td>
  <td class=xl67 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
  <td class=xl67 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
  <td class=xl67 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl67 style='height:15.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Total</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 1</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 2</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 3</span></b></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Fenton</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">216</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">66</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">76</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Tyler Graves</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">217</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">65</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">73</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">79</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Morey</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">220</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">72</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Tim Bayles</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">222</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">70</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">78</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Ed Elliott</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">229</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">75</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Brooks Klein</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">231</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">71</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">83</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dan Needham</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">231</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">85</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">64</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">82</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Mark Parsley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">236</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">80</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">78</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">78</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Jake Nole</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">237</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">78</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">82</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Rosas</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">237</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">86</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Bob Langley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">242</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">79</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">82</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Kurt Vanderyt</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">243</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">74</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Al Kucharski</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">244</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">80</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">83</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Lyn Smith</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">244</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">78</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">66</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">100</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Paul Valvo</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">250</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">76</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">82</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">92</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Al Yarbrough</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">254</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">85</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Rick
  McFarland</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">258</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">80</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">90</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Bob Swagerty</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">269</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">90</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">92</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">87</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">John Graves</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">270</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">84</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">91</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">95</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Randy
  Wheatley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">291</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">83</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">95</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">113</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">&nbsp;</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl68 style='height:15.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">Average</font></span></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">242.1</font></span></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">78.4</font></span></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">78.3</font></span></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">85.4</font></span></td>
 </tr>
</table>
<br><br>
  <table class="MsoNormalTable" border="1" cellspacing="0" cellpadding="0" style="width: 430; border-collapse: collapse; border: medium none; margin-left: 4.65pt" bordercolor="#737373">
 <col width=104 style='mso-width-source:userset;mso-width-alt:3803;width:78pt'>
 <col width=64 span=4 style='width:48pt'>
 <tr height=36 style='height:27.0pt'>
      <td nowrap style="width: 132; height: 27.75pt; border-style: solid; border-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 22.0pt; font-family: Arial,sans-serif; color: white">Gross</span></td>
  <td class=xl69 style='border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; height:27.75pt; border-top-style:solid; border-top-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; height:27.75pt; border-top-style:solid; border-top-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; height:27.75pt; border-top-style:solid; border-top-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; height:27.75pt; border-top-style:solid; border-top-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">&nbsp;</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Total</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 1</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 2</span></b></td>
  <td class=xl68 style='border-top:medium none;border-left:medium none; ; height:15.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt"><b>
  <span style="font-family: Arial,sans-serif; color: white">Day 3</span></b></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Brooks Klein</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">231</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">71</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">77</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">83</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Ed Elliott</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">241</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">79</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">81</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Morey</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">261</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">85</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Fenton</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">265</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">82</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">90</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">93</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dan Needham</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">266</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">97</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">75</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">94</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Mark Parsley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">270</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">91</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">89</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">90</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Tim Bayles</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">281</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">94</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">89</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">98</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Rick
  McFarland</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">282</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">96</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">98</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Tyler Graves</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">285</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">88</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">95</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">102</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Jake Nole</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">292</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">96</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">100</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">96</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Bob Swagerty</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">311</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">104</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">105</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">102</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Paul Valvo</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">312</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">97</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">102</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">113</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Kurt Vanderyt</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">316</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">106</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">98</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">112</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Al Kucharski</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">317</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">105</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">105</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">107</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Bob Langley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">317</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">104</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">106</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">107</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Dave Rosas</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">333</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">109</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">106</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">118</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">John Graves</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">339</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">108</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">113</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">118</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Lyn Smith</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">340</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">110</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">98</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">132</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Al Yarbrough</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">350</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">113</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">117</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">120</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">Randy
  Wheatley</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">359</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">106</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">117</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">136</span></td>
 </tr>
 <tr height=17 style='height:12.75pt'>
  <td height=17 class=xl67 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
  <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">&nbsp;</span></td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
  <td class=xl69 style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000" align="center">
  <p class="MsoNormal" align="center" style="line-height: normal; margin-bottom: .0001pt">&nbsp;</td>
 </tr>
 <tr height=21 style='height:15.75pt'>
  <td height=21 class=xl68 style='height:12.75pt;border-top:medium none; ; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in; width:132; border-left-style:solid; border-left-width:1.5pt' nowrap bgcolor="#000000">
  <p>
  <span style="font-family: Arial,sans-serif; font-weight:700">
  <font color="#FFFFFF" size="3">Average</font></span></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p><font color="#FFFFFF" size="3">
  <span style="font-family: Arial,sans-serif; font-weight: 700">298.4</span></font></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p><font color="#FFFFFF" size="3">
  <span style="font-family: Arial,sans-serif; font-weight: 700">97.3</span></font></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p><font color="#FFFFFF" size="3">
  <span style="font-family: Arial,sans-serif; font-weight: 700">96.7</span></font></td>
  <td class=xl70 align=center style='border-top:medium none;border-left:medium none; ; height:12.75pt; border-right-style:solid; border-right-width:1.5pt; border-bottom-style:solid; border-bottom-width:1.5pt; padding-left:5.4pt; padding-right:5.4pt; padding-top:0in; padding-bottom:0in' nowrap bgcolor="#000000">
  <p><font color="#FFFFFF" size="3">
  <span style="font-family: Arial,sans-serif; font-weight: 700">104.4</span></font></td>
 </tr>
</table>
</div>