<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2000 Scores</b></font>
<br>
&nbsp;</p>
<div align="center">
  <center>
  <table border="1" cellpadding="0" cellspacing="0" width="567" style="border-collapse: collapse" bordercolor="#737373">
    <colgroup>
      <col width="106" style="width: 80pt"><col width="83" style="width: 62pt">
      <col width="82" style="width: 62pt"><col width="72" style="width: 54pt">
      <col width="73" style="width: 55pt"><col width="71" style="width: 53pt">
      <col width="58" style="width: 44pt">
    </colgroup>
    <tr height="42" style="height:31.5pt">
      <td height="42" width="106" style="height: 31.5pt; width: 107; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Name</font></td>
      <td width="83" style="width: 103; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Gross</font></td>
      <td width="82" style="width: 78; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Handicap</font></td>
      <td width="72" style="width: 62; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Net</font></td>
      <td width="73" style="width: 75; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Cum Gross</font></td>
      <td width="71" style="width: 67; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; white-space: normal; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Cum&nbsp;&nbsp; Net</font></td>
      <td width="58" style="width: 75; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom-style: solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">
      <font color="#FFFFFF">Award</font></td>
    </tr>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 103; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 78; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
      <td style="font-size: 12.0pt; font-weight: 700; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border-left-style: solid; border-left-color: inherit; border-right-style: solid; border-right-color: inherit; border-top-style: solid; border-top-color: inherit; border-bottom: medium solid; padding-left: 1px; padding-right: 1px; padding-top: 1px">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 567">
    <colgroup>
      <col width="106" style="width: 80pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="547" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/28/2000&nbsp;&nbsp;&nbsp;&nbsp; Course: Entrada&nbsp;&nbsp;&nbsp;&nbsp; Slope: 
      123&nbsp;&nbsp;&nbsp;&nbsp; Par: 72</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="567">
    <colgroup>
      <col width="106" style="width: 80pt"><col width="83" style="width: 62pt">
      <col width="82" style="width: 62pt"><col width="72" style="width: 54pt">
      <col width="73" style="width: 55pt"><col width="71" style="width: 53pt">
      <col width="58" style="width: 44pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="width: 103; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" x:fmla="=C1+D1" bordercolor="#737373">
      <font color="#FFFFFF">100</font></td>
      <td style="width: 78; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">20</font></td>
      <td style="width: 62; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">80</font></td>
      <td style="width: 75; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">294</font></td>
      <td style="width: 67; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">234</font></td>
      <td style="width: 75; font-size: 11.0pt; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">2nd</font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Buckley, Pat</font></td>
      <td x:fmla="=C2+D2" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">102</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">20</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">82</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">302</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">241</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Dah, Terry</font></td>
      <td x:fmla="=C3+D3" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">83</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">10</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">73</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">253</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">221</font></td>
      <td style="font-size: 8.0pt; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <b>
      <font color="#FFFFFF">Champion</font></b></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Jameson, Tom</font></td>
      <td x:fmla="=C4+D4" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">97</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">22</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">75</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">304</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">242</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td x:fmla="=C5+D5" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">109</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">26</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">83</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">DNF</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">DNF</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td x:fmla="=C6+D6" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">99</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">24</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">75</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">DNF</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">DNF</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Phillips, Tom</font></td>
      <td x:fmla="=C7+D7" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">92</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">18</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">74</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">285</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">235</font></td>
      <td style="font-size: 11.0pt; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">3rd</font></td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td x:fmla="=C8+D8" style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">113</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">32</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">
      <font color="#FFFFFF">81</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">
      <font color="#FFFFFF">382</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">
      <font color="#FFFFFF">290</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td colspan="2" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:num="99.375" x:fmla="=AVERAGE(B1:B8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">99.4</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:fmla="=AVERAGE(C1:C8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">21.5</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="font-style: italic; font-family: Arial, sans-serif; color: windowtext; font-size: 10.0pt; font-weight: 400; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:num="77.875" x:fmla="=AVERAGE(D1:D8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">77.9</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="62" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="67" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="75" bordercolor="#737373">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 567">
    <colgroup>
      <col width="106" style="width: 80pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; width: 548; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/27/2000&nbsp;&nbsp;&nbsp;&nbsp; Course: Oasis&nbsp;&nbsp;&nbsp;&nbsp; Slope: 
      130&nbsp;&nbsp;&nbsp;&nbsp; Par: 71</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="567">
    <colgroup>
      <col width="106" style="width: 80pt"><col width="83" style="width: 62pt">
      <col width="82" style="width: 62pt"><col width="72" style="width: 54pt">
      <col width="73" style="width: 55pt"><col width="71" style="width: 53pt">
      <col width="58" style="width: 44pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td height="19" width="106" style="height: 14.25pt; width: 107; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="width: 103; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">87</font></td>
      <td style="width: 78; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">22</font></td>
      <td width="72" style="width: 62; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">65</font></td>
      <td width="73" style="width: 75; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">194</font></td>
      <td width="71" style="width: 67; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">154</font></td>
      <td width="58" style="width: 75; color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Buckley, Pat</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">91</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">21</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">70</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">200</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">159</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Dah, Terry</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">80</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">12</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">68</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">170</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">148</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Jameson, Tom</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">95</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">22</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">73</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">207</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">167</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">99</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">27</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">72</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">x</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">x</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">94</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">24</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">70</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">x</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">x</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Phillips, Tom</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">87</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">12</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">69</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">193</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">161</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">129</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">32</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">97</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">269</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">209</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td colspan="2" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 103; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:num="95.25" x:fmla="=AVERAGE(B1:B8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">95.3</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:fmla="=AVERAGE(C1:C8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">21.5</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:fmla="=AVERAGE(D1:D8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">73.0</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse; width: 567">
    <colgroup>
      <col width="106" style="width: 80pt">
    </colgroup>
    <tr height="21" style="height:15.75pt">
      <td height="21" style="height: 15.75pt; width: 548; font-size: 12.0pt; font-weight: 700; text-decoration: underline; text-underline-style: single; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-style: normal; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Date:&nbsp; 10/26/2000&nbsp;&nbsp;&nbsp;&nbsp; Course: Rio Secco&nbsp;&nbsp;&nbsp;&nbsp; Slope: 
      138&nbsp;&nbsp;&nbsp;&nbsp; Par: 72</font></td>
    </tr>
  </table>
  </center>
</div>
<div align="center">
  <center>
  <table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="567">
    <colgroup>
      <col width="106" style="width: 80pt"><col width="83" style="width: 62pt">
      <col width="82" style="width: 62pt"><col width="72" style="width: 54pt">
      <col width="73" style="width: 55pt"><col width="71" style="width: 53pt">
      <col width="58" style="width: 44pt">
    </colgroup>
    <tr height="19" style="height:14.25pt">
      <td height="19" width="106" style="height: 14.25pt; width: 107; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Bayles, Tim</font></td>
      <td style="width: 103; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">107</font></td>
      <td style="width: 78; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">18</font></td>
      <td width="72" style="width: 62; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">89</font></td>
      <td width="73" style="width: 75; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td width="71" style="width: 67; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td width="58" style="width: 75; color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Buckley, Pat</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">109</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">20</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">89</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Dah, Terry</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">90</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">10</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">80</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Jameson, Tom</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">112</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">18</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">94</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Langley, Bob</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">DNC</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">23</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">DNC</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Moore, Terry</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">DNC</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">24</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">DNC</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Phillips, Tom</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">106</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">14</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">92</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">Smith, Lyn</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">
      <font color="#FFFFFF">140</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">
      <font color="#FFFFFF">28</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">
      <font color="#FFFFFF">112</font></td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; font-size: 11.0pt; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; font-style: normal; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td colspan="2" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 103; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Gross:</font></td>
      <td x:num="110.66666666666667" x:fmla="=AVERAGE(B1:B8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">110.7</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Handicap:</font></td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:num="19.375" x:fmla="=AVERAGE(C1:C8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">19.4</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
    <tr height="19" style="height:14.25pt">
      <td height="19" style="height: 14.25pt; color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 107; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: left; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="103" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">Avg. Net:</font></td>
      <td style="font-style: italic; font-family: Arial, sans-serif; color: windowtext; font-size: 10.0pt; font-weight: 400; text-decoration: none; text-align: general; vertical-align: bottom; white-space: nowrap; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" width="78" bordercolor="#737373" bgcolor="#737373">&nbsp;</td>
      <td x:num="92.666666666666671" x:fmla="=AVERAGE(D1:D8)" style="font-size: 11.0pt; font-style: italic; font-family: Arial, sans-serif; text-align: center; color: windowtext; font-weight: 400; text-decoration: none; vertical-align: bottom; white-space: nowrap; width: 62; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373" bgcolor="#737373">
      <font color="#FFFFFF">92.7</font></td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 67; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
      <td style="color: windowtext; font-size: 10.0pt; font-weight: 400; font-style: normal; text-decoration: none; font-family: Arial; text-align: general; vertical-align: bottom; white-space: nowrap; width: 75; border: 1px solid; padding-left: 1px; padding-right: 1px; padding-top: 1px" bordercolor="#737373">&nbsp;</td>
    </tr>
  </table>
  </center>
</div>