<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2007 Scores</b></font>
<br>
&nbsp;</p>

<div align="center">
  <center>
  <table class="MsoNormalTable" border="1" cellspacing="0" cellpadding="0" style="width: 430; border-collapse: collapse; border: medium none; margin-left: 4.65pt" bordercolor="#737373">
    <tr style="height: 27.75pt">
      <td nowrap style="width: 132; height: 27.75pt; border-style: solid; border-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 22.0pt; font-family: Arial,sans-serif; color: white">
      NET</span></td>
      <td nowrap style="width: 65; height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 22.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td width="65" nowrap style="height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp; </span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">&nbsp;</td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">&nbsp;</td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
    </tr>
    <tr style="height: 15.75pt">
      <td nowrap style="width: 132; height: 15.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal" align="center"><b>
      <span style="font-family: Arial,sans-serif; color: white">Total</span></b></td>
      <td width="65" nowrap style="height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 1</span></b></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 2</span></b></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 3</span></b></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Al Kucharski</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      218</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      69</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      71</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Stewart Sampson</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      219</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      63</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      74</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      82</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jimmy McKinzie</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      221</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      66</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      72</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jim Gaines</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      222</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      69</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      70</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jake Nole</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      222</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      72</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      70</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dave Morey</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      226</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      74</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      67</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      85</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Paul Valvo</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      226</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      73</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      76</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Tim Bayles</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      227</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      73</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      74</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Craig Hauschildt</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      229</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      62</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      84</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dan Needham</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      229</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      75</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      76</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Bob Langley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      230</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      75</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Terry Sucher</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      230</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      74</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      79</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dave Fenton</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      231</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      72</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      81</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Greg Austin</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      232</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      72</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      71</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Ed Elliott</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      233</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      73</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Rich Hauschildt</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      233</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      76</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Rick McFarland</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      234</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      81</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      73</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Randy Wheatley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      236</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      75</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      84</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Will Williams</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      237</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      76</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Terry Moore</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      239</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      82</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Pat Buckley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      241</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      81</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      82</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Connie Black</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      242</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      78</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      84</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Al Yarbrough</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      243</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      77</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      75</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      91</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Allen Frank</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      249</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      86</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Mike Sampson</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      264</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      90</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      87</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      87</span></td>
    </tr>
    <tr>
      <td nowrap style="width: 132; height: 13.5pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      John Graves</span></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      294</span></td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      95</span></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      106</span></td>
    </tr>
    <tr style="height: 13.5pt">
      <td nowrap style="width: 132; height: 13.5pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">&nbsp;</td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">&nbsp;</td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">&nbsp;</td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">&nbsp;</td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">&nbsp;</td>
    </tr>
    <tr style="height: 13.5pt">
      <td nowrap style="width: 132; height: 13.5pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" bgcolor="#000000">
      <font color="#FFFFFF" size="3">
      <span style="font-family: Arial,sans-serif; font-weight: 700">Average</span></font></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <font size="2" color="#FFFFFF">
      <span style="font-family: Arial,sans-serif">234.9</span></font></td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <font size="2" color="#FFFFFF">
      <span style="font-family: Arial,sans-serif">75.5</span></font></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <font size="2" color="#FFFFFF">
      <span style="font-family: Arial,sans-serif">78.3</span></font></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center" bgcolor="#000000">
      <font size="2" color="#FFFFFF">
      <span style="font-family: Arial,sans-serif">81.1</span></font></td>
    </tr>
  </table>
  </center>
</div>


<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<div align="center">
  <center>

  <p></p>

  </center>
</div>



<p>


&nbsp;</p>


<div align="center">
  <center>
  <table class="MsoNormalTable" border="1" cellspacing="0" style="width: 430; border-collapse: collapse; border: medium none; margin-left: 4.65pt" bordercolor="#737373" cellpadding="0">
    <tr style="height: 27.75pt">
      <td nowrap style="width: 132; height: 27.75pt; border-style: solid; border-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 22.0pt; font-family: Arial,sans-serif; color: white">
      Gross</span></td>
      <td nowrap style="width: 65; height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td width="65" nowrap style="height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td width="65" nowrap style="height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 27.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top-style: solid; border-top-width: 1.5pt; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
    </tr>
    <tr style="height: 15.75pt">
      <td nowrap style="width: 132; height: 15.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      &nbsp;</span></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Total</span></b></td>
      <td width="65" nowrap style="height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 1</span></b></td>
      <td width="65" nowrap style="height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 2</span></b></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Day 3</span></b></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Ed Elliott</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      252</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      80</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Rick McFarland</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      259</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      82</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      88</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dan Needham</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      264</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      87</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      88</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dave Fenton</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      271</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      85</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      94</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      92</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Terry Sucher</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      272</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      87</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      92</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jim Gaines</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      274</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      86</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      100</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      88</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jake Nole</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      274</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      87</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      98</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Dave Morey</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      275</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      90</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      83</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      102</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Tim Bayles</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      281</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      90</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      98</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Allen Frank</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      281</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      90</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      97</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      94</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Al Kucharski</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      282</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      100</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Paul Valvo</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      287</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      96</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      98</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Rich Hauschildt</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      290</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      94</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      99</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      97</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Randy Wheatley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      291</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      93</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      95</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      103</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Greg Austin</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      292</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      91</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      91</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      110</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Will Williams</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      297</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      102</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      96</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      99</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Connie Black</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      299</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      96</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      99</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      104</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Stewart Sampson</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      301</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      102</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      110</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Terry Moore</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      303</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      100</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      99</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      104</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Bob Langley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      309</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      100</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      104</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      105</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Pat Buckley</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      313</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      101</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      105</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      107</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Craig Hauschildt</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      314</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      89</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      113</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      112</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Jimmy McKinzie</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      328</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      101</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      119</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      108</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Mike Sampson</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      343</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      115</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      114</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      114</span></td>
    </tr>
    <tr style="height: 12.75pt">
      <td nowrap style="width: 132; height: 12.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      Al Yarbrough</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      351</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      113</span></td>
      <td width="65" nowrap style="height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      111</span></td>
      <td nowrap style="width: 65; height: 12.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      127</span></td>
    </tr>
    <tr style="height: 13.5pt">
      <td nowrap style="width: 132; height: 13.5pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      John Graves</span></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      353</span></td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      114</span></td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      112</span></td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" align="center" style="margin-bottom:0in;margin-bottom:.0001pt;
  text-align:center;line-height:normal">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      127</span></td>
    </tr>
    <tr style="height: 13.5pt">
      <td nowrap style="width: 132; height: 13.5pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">&nbsp;</td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td width="65" nowrap style="height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
      <td nowrap style="width: 65; height: 13.5pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">&nbsp;</td>
    </tr>
    <tr style="height: 15.75pt">
      <td nowrap style="width: 132; height: 15.75pt; border-left-style: solid; border-left-width: 1.5pt; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in">
      <p class="MsoNormal" style="margin-bottom:0in;margin-bottom:.0001pt;line-height:
  normal"><b><span style="font-family: Arial,sans-serif; color: white">Average</span></b></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      294.5</span></td>
      <td width="65" nowrap style="height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      94.5</span></td>
      <td width="65" nowrap style="height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      98.3</span></td>
      <td nowrap style="width: 65; height: 15.75pt; border-left: medium none; border-right-style: solid; border-right-width: 1.5pt; border-top: medium none; border-bottom-style: solid; border-bottom-width: 1.5pt; padding-left: 5.4pt; padding-right: 5.4pt; padding-top: 0in; padding-bottom: 0in" align="center">
      <p class="MsoNormal" style="line-height: normal; margin-bottom: .0001pt">
      <span style="font-size: 10.0pt; font-family: Arial,sans-serif; color: white">
      101.6</span></td>
    </tr>
  </table>
  </center>
</div>