<hr>
<p align="center"><font color="#FFFFFF" size="5"><b>2012 Scores</b></font>
<br></p>
      
<div align="center">
<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  NET</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr> 
 <tr><td>Jimmy McKinzie</td><td>210</td><td>79</td><td>66</td><td>65</td><td>&nbsp;</td></tr>
 <tr><td>Rick McFarland</td><td>211</td><td>79</td><td>62</td><td>70</td><td>&nbsp;</td></tr>
 <tr><td>Eric Larson</td><td>214</td><td>77</td><td>69</td><td>68</td><td>Tie</td></tr>
 <tr><td>Mark Parsley</td><td>214</td><td>80</td><td>67</td><td>67</td><td>&nbsp;</td></tr>
 <tr><td>Dave Rosas</td><td>219</td><td>76</td><td>71</td><td>72</td><td>&nbsp;</td></tr>
 <tr><td>Kirk Smart</td><td>221</td><td>69</td><td>68</td><td>84</td><td>&nbsp;</td></tr>
 <tr><td>Robert Guthrie</td><td>224</td><td>78</td><td>71</td><td>75</td><td>&nbsp;</td></tr>
 <tr><td>Dan Needham</td><td>229</td><td>84</td><td>73</td><td>72</td><td>&nbsp;</td></tr>
 <tr><td>Gary Frick</td><td>231</td><td>73</td><td>74</td><td>84</td><td>Tie</td></tr>
 <tr><td>Randy Wheatley</td><td>231</td><td>77</td><td>72</td><td>82</td><td>&nbsp;</td></tr>
 <tr><td>Rene Almaraz</td><td>234</td><td>76</td><td>76</td><td>82</td><td>Tie</td></tr>
 <tr><td>Omel Cardenas</td><td>234</td><td>85</td><td>72</td><td>77</td><td>&nbsp;</td></tr>
 <tr><td>David Bunker</td><td>235</td><td>82</td><td>74</td><td>79</td><td>Tie</td></tr>
 <tr><td>Frank Carriere</td><td>235</td><td>84</td><td>74</td><td>77</td><td>&nbsp;</td></tr>
 <tr><td>Connie Black</td><td>238</td><td>79</td><td>76</td><td>83</td><td>&nbsp;</td></tr>
 <tr><td>Bob Rhinehart</td><td>240</td><td>83</td><td>85</td><td>72</td><td>&nbsp;</td></tr>
 <tr><td>Gavin Russo</td><td>245</td><td>79</td><td>74</td><td>92</td><td>&nbsp;</td></tr>
 <tr><td>Jim Coffey</td><td>246</td><td>87</td><td>76</td><td>83</td><td>&nbsp;</td></tr>
 <tr><td>Tim Bayles</td><td>250</td><td>78</td><td>82</td><td>90</td><td>&nbsp;</td></tr>
 <tr><td>Bob Langley</td><td>251</td><td>84</td><td>82</td><td>85</td><td>&nbsp;</td></tr>
 <tr><td>Paul Valvo</td><td>254</td><td>79</td><td>89</td><td>86</td><td>&nbsp;</td></tr>
 <tr><td>Jason Carmack</td><td>257</td><td>95</td><td>77</td><td>85</td><td>&nbsp;</td></tr>
 <tr><td>Roland Gonzales</td><td>260</td><td>95</td><td>80</td><td>85</td><td>&nbsp;</td><td></td></tr>
</table>

















<br/><br/>






<table width="430" class="score">
<tr>
  <td colwidth="6" style="height: 27.0pt; width: 134pt; font-size: 22.0pt;">
  Gross</td>
</tr>
<tr>
  <td colwidth="6"></td>
</tr>
<tr>
  <th>Player</th>
  <th>Total</th>
  <th>Day 1</th>
  <th>Day 2</th>
  <th>Day 3</th>
  <th></th>
</tr> 
<tr><td>Rick McFarland</td><td>251</td><td>92</td><td>75</td><td>84</td><td>&nbsp;</td></tr>
<tr><td>Mark Parsley</td><td>254</td><td>93</td><td>80</td><td>81</td><td>&nbsp;</td></tr>
<tr><td>Gary Frick</td><td>273</td><td>87</td><td>88</td><td>98</td><td>&nbsp;</td></tr>
<tr><td>Dan Needham</td><td>278</td><td>100</td><td>89</td><td>89</td><td>&nbsp;</td></tr>
<tr><td>David Bunker</td><td>281</td><td>97</td><td>89</td><td>95</td><td>&nbsp;</td></tr>
<tr><td>Frank Carriere</td><td>287</td><td>101</td><td>91</td><td>95</td><td>&nbsp;</td></tr>
<tr><td>Gavin Russo</td><td>288</td><td>93</td><td>88</td><td>107</td><td>&nbsp;</td></tr>
<tr><td>Robert Guthrie</td><td>291</td><td>100</td><td>93</td><td>98</td><td>&nbsp;</td></tr>
<tr><td>Jason Carmack</td><td>293</td><td>107</td><td>89</td><td>97</td><td>&nbsp;</td></tr>
<tr><td>Connie Black</td><td>296</td><td>98</td><td>95</td><td>103</td><td>&nbsp;</td></tr>
<tr><td>Eric Larson</td><td>303</td><td>106</td><td>98</td><td>99</td><td>&nbsp;</td></tr>
<tr><td>Jimmy McKinzie</td><td>308</td><td>111</td><td>98</td><td>99</td><td>Tie</td></tr>
<tr><td>Randy Wheatley</td><td>308</td><td>102</td><td>97</td><td>109</td><td>&nbsp;</td></tr>
<tr><td>Rene Almaraz</td><td>309</td><td>101</td><td>100</td><td>108</td><td>&nbsp;</td></tr>
<tr><td>Tim Bayles</td><td>311</td><td>98</td><td>102</td><td>111</td><td>&nbsp;</td></tr>
<tr><td>Omel Cardenas</td><td>312</td><td>111</td><td>97</td><td>104</td><td>Tie</td></tr>
<tr><td>Dave Rosas</td><td>312</td><td>107</td><td>101</td><td>104</td><td>&nbsp;</td></tr>
<tr><td>Kirk Smart</td><td>326</td><td>104</td><td>102</td><td>120</td><td>&nbsp;</td></tr>
<tr><td>Jim Coffey</td><td>327</td><td>114</td><td>102</td><td>111</td><td>&nbsp;</td></tr>
<tr><td>Bob Rhinehart</td><td>332</td><td>113</td><td>115</td><td>104</td><td>&nbsp;</td></tr>
<tr><td>Paul Valvo</td><td>337</td><td>106</td><td>116</td><td>115</td><td>&nbsp;</td></tr>
<tr><td>Bob Langley</td><td>341</td><td>114</td><td>111</td><td>116</td><td>&nbsp;</td></tr>
<tr><td>Roland Gonzales</td><td>361</td><td>128</td><td>113</td><td>120</td><td></td></tr>
</table>

</div>