<center>
<table border="0" cellpadding="0" cellspacing="0" style="border-collapse: collapse" width="90%" id="AutoNumber3" bordercolor="#C0C0C0">
  <tr> 
    <td width="20%" align="center">
    <font color="#FFFFFF" SIZE="5">10/29 - 11/1/2015</font>
    </td>
    
    <td width="20%" align="center"><a href="index.html">
    <img name="home" src="home.gif" border="0" alt width="62" height="17"></a>
    </td>
    
    <td width="20%" align="center"><a href="pics.html">
    <img name="pics" src="pics.gif" border="0" alt width="42" height="16"></a>
    </td>
    
    <td width="20%" bordercolor="#C0C0C0" align="center"><a href="scoresCurrent.html">
    <img name="scores" src="scores.gif" border="0" alt width="65" height="16"></a>
    </td>
    
<!--td width="17%" bordercolor="#C0C0C0" align="center"><a href="talk.htm">
    <img name="talk" src="talk.gif" border="0" alt width="48" height="17"></a>
</td-->

    <td width="20%" bordercolor="#C0C0C0" align="center"><a href="links.html">
    <img name="links" src="links.gif" border="0" alt width="56" height="18"></a>
    </td>
    
<!--td width="17%" bordercolor="#C0C0C0" align="center">
    <a href="travel.htm">
                <img name="travel" src="travel.gif" border="0" alt="" width="67" height="17"></a>
</td-->

  </tr>
</table>
</center>
